name: cepler-deploy
"on":
- push
jobs:
  deploy-testflight:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        persist-credentials: false
    - id: prepare-cepler
      uses: bodymindarts/cepler-action@main
      with:
        config_path: cepler.yml
        environment: testflight
        prepare: true
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      uses: k14s/setup-k14s-action@v1
      with:
        only: ytt, kapp
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      name: render-secrets
      env:
        SECRETS: '{"app_registry":{"password":"${{ secrets.DOCKERHUB_PASSWORD }}"}}'
      run: |
        cat <<EOF > secrets.yml
        #@data/values
        #@ load("@ytt:overlay", "overlay")
        #@overlay/match-child-defaults missing_ok=True
        ---
        ${SECRETS}
        EOF
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      run: ytt -f k8s/cf-for-k8s/config -f k8s/cf-values.yml -f secrets.yml > rendered.yml
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      id: deploy-testflight
      env:
        KAPP_KUBECONFIG_YAML: '{"apiVersion":"v1","clusters":[{"cluster":{"certificate-authority-data":"${{ secrets.TESTFLIGHT_CA }}","server":"${{ secrets.TESTFLIGHT_SERVER"},"name":"testflight"}],"contexts":[{"context":{"cluster":"testflight","user":"testflight-user"},"name":"testflight"}],"current-context":"testflight","kind":"Config","preferences":{},"users":[{"name":"testflight-user","user":{"token":"${{ secrets.TESTFLIGHT_TOKEN }}"}}]}'
      run: kapp -y deploy -f rendered.yml -a testflight-cf
    - if: ${{ steps.deploy-testflight.conclusion  == 'Success' }}
      name: cepler record
      uses: bodymindarts/cepler-action@main
      with:
        config_path: cepler.yml
        environment: testflight
        record: true
    - if: ${{ steps.deploy-testflight.conclusion  == 'Success' }}
      name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: master
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        persist-credentials: false
    - id: prepare-cepler
      uses: bodymindarts/cepler-action@main
      with:
        config_path: cepler.yml
        environment: staging
        prepare: true
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      uses: k14s/setup-k14s-action@v1
      with:
        only: ytt, kapp
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      name: render-secrets
      env:
        SECRETS: '{"app_registry":{"password":"${{ secrets.DOCKERHUB_PASSWORD }}"}}'
      run: |
        cat <<EOF > secrets.yml
        #@data/values
        #@ load("@ytt:overlay", "overlay")
        #@overlay/match-child-defaults missing_ok=True
        ---
        ${SECRETS}
        EOF
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      run: ytt -f k8s/cf-for-k8s/config -f k8s/cf-values.yml -f secrets.yml > rendered.yml
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      id: deploy-staging
      env:
        KAPP_KUBECONFIG_YAML: '{"apiVersion":"v1","clusters":[{"cluster":{"certificate-authority-data":"${{ secrets.STAGING_CA }}","server":"${{ secrets.STAGING_SERVER"},"name":"staging"}],"contexts":[{"context":{"cluster":"staging","user":"staging-user"},"name":"staging"}],"current-context":"staging","kind":"Config","preferences":{},"users":[{"name":"staging-user","user":{"token":"${{ secrets.STAGING_TOKEN }}"}}]}'
      run: kapp -y deploy -f rendered.yml -a staging-cf
    - if: ${{ steps.deploy-staging.conclusion  == 'Success' }}
      name: cepler record
      uses: bodymindarts/cepler-action@main
      with:
        config_path: cepler.yml
        environment: staging
        record: true
    - if: ${{ steps.deploy-staging.conclusion  == 'Success' }}
      name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: master
